#!/bin/bash

#
# description: makes contact sheets for your tv shows and movies using
#              your kodi sqlite files as source material.
#
# author:      davx8342@gmail.com
# version:     0.3 ALPHA
#
VERSION="0.3 ALPHA"

#
# path to your kodi db files
#
dbpath="./db"

#
# output path to your html
#
htmlout="/var/www/html/kodisheet"

#
# how many days back the recently added goes
#
lastDays="7"

#
# what we process, your options are tvshow or movie or both
#
mediatypes="tvshow movie"

if [ ! -d "$dbpath" ]; then
   echo You haven\'t created your db directory, you need to create this
   echo and put your kodi database files in there for this script to work.
   exit
fi

if [ ! -d "$htmlout" ]; then
   echo Your html output directory does not exist.
   exit
fi

#
# we save our images in a particular structure, create the structure if any
# of these directories don't already exist.
#
checkdirs="$htmlout/images $htmlout/images/tvshowposters $htmlout/images/movieposters $htmlout/images/tvshowfanart $htmlout/images/moviefanart $htmlout/images/tvshowbanners $htmlout/tvshow $htmlout/movie $htmlout/genre"

#
# footer
#
footer="Generated by <a href=\"https://github.com/davx8342/kodisheet\">kodisheet</a> $VERSION"

#
# some basic metrics
#
movieCount=`sqlite3 $dbpath/MyVideos107.db "SELECT count() from movie"`
tvCount=`sqlite3 $dbpath/MyVideos107.db "SELECT count() from tvshow"`

#
# remove the genre index
#
if [ -f "$htmlout/genre/index.html" ]; then
   rm "$htmlout/genre/index.html"
fi

for dir in $checkdirs; do
   if [ ! -d "$dir" ]; then
      echo "INFO: $dir doesn't exist, will try and create it"
      mkdir -p $dir
   fi
done

#
# if we have files without poster art we need to substitute something or we get broken images
#
convert -size 150x221 xc:black $htmlout/images/tvshowbanners/unknown.jpg
convert -size 150x221 xc:black $htmlout/images/tvshowposters/unknown.jpg
convert -size 150x221 xc:black $htmlout/images/movieposters/unknown.jpg



genres=`sqlite3 $dbpath/MyVideos107.db "SELECT genre_id from genre"`
genrenav=""

for genre in $genres; do
   name=`sqlite3 $dbpath/MyVideos107.db "SELECT name from genre where genre_id=$genre"`
   out="$htmlout/genre/$genre.html"

   #
   # count to see if we have media in this genre, if we don't we exclude it
   #
   count=`sqlite3 $dbpath/MyVideos107.db "SELECT count() from genre_link where genre_id=$genre"`
   if [ "$count" != "0" ]; then
      genrenav="<a href=\"$genre.html\">$name</a> | $genrenav"

      if [ -f "$out" ]; then
         rm $out
      fi
      touch $out

      echo "<html><head><title>$name</title>" >> $out
      echo "<link rel=\"stylesheet\" href=\"../kodisheet.css\" type=\"text/css\">" >> $out
      echo "</head><body>" >> $out
      echo "<p class=\"navigaton\">" >> $out
      echo "<font class=\"giantheading\">Genre: $name</font>" >> $out
      echo "<br /><br />" >> $out
   fi
done

#
# remove the last 3 digits, basically ' | '
#
genrenav=${genrenav::-3}

for genre in $genres; do
   if [ -f "$htmlout/genre/$genre.html" ]; then
      echo "<font class=\"heading\">" >> $htmlout/genre/$genre.html
      echo "$genrenav" >> $htmlout/genre/$genre.html
      echo "</font>" >> $htmlout/genre/$genre.html
   fi
done

echo "<html><head><title>genres</title>" >> $htmlout/genre/index.html
echo "<link rel=\"stylesheet\" href=\"../kodisheet.css\" type=\"text/css\">" >> $htmlout/genre/index.html
echo "</head><body>" >> $htmlout/genre/index.html
echo "<p class=\"navigaton\">" >> $htmlout/genre/index.html
echo "<font class=\"giantheading\">All Genres</font>" >> $htmlout/genre/index.html
echo "<br /><br />" >> $htmlout/genre/index.html
echo "<font class=\"heading\">$genrenav" >> $htmlout/genre/index.html
echo "</font></p></body></html>" >> $htmlout/genre/index.html

for mediatype in $mediatypes; do

   if [ "$mediatype" == "tvshow" ]; then
      id="idShow"
      table="$mediatype"
      indextitle="TV Shows"
   fi

   if [ "$mediatype" == "movie" ]; then
      id="idMovie"
      table="$mediatype"
      indextitle="Movies"
   fi

   idList=`sqlite3 $dbpath/MyVideos107.db "SELECT $id from $table ORDER BY c00"`

   if [ -f "$htmlout/$mediatype.html" ]; then
      rm $htmlout/$mediatype.html
   fi
   touch $htmlout/$mediatype.html

   echo "<html><head><title>$indextitle</title>" >> $htmlout/$mediatype.html
   echo "<link rel=\"stylesheet\" href=\"kodisheet.css\" type=\"text/css\">" >> $htmlout/$mediatype.html
   echo "</head><body>" >> $htmlout/$mediatype.html
   echo "<p class=\"navigaton\">" >> $htmlout/$mediatype.html
   echo "<br /><br />" >> $htmlout/$mediatype.html
   echo "<font class=\"giantheading\">" >> $htmlout/$mediatype.html

   echo "<a href=\"index.html\">Home</a>" >> $htmlout/$mediatype.html
   echo " | " >> $htmlout/$mediatype.html

   if [ "$mediatype" == "tvshow" ]; then
      echo "TV Shows [$tvCount]" >> $htmlout/$mediatype.html
   else
      echo "<a href=\"tvshow.html\">TV Shows</a> [$tvCount]" >> $htmlout/$mediatype.html
   fi

   echo " | " >> $htmlout/$mediatype.html

   if [ "$mediatype" == "movie" ]; then
      echo "Movies [$movieCount]" >> $htmlout/$mediatype.html
   else
      echo "<a href=\"movie.html\">Movies</a> [$movieCount]" >> $htmlout/$mediatype.html
   fi

   echo " | " >> $htmlout/$mediatype.html

   echo "<a href=\"genre/index.html\">All Genres</a>" >> $htmlout/$mediatype.html

   echo " | " >> $htmlout/$mediatype.html

   echo "<a href=\"recent.html\">Last $lastDays days</a>" >> $htmlout/$mediatype.html
   echo "<br /><br /></font>" >> $htmlout/$mediatype.html

   if [ "$mediatype" == "tvshow" ]; then
      convert -size 130x25 xc:blue $htmlout/blue.jpg
      convert -size 120x25 xc:orange $htmlout/orange.jpg
      convert -font Arial -pointsize 18 -fill white -background blue -gravity center -size 130x25 caption:"no. of episodes" $htmlout/blue.jpg +swap -gravity west -composite $htmlout/episodes.jpg
      convert -fill white -font Arial -pointsize 18 -background orange -gravity center -size 120x25 caption:"no. of seasons" $htmlout/orange.jpg +swap -gravity west -composite $htmlout/seasons.jpg
      echo "<img src=\"episodes.jpg\"> <img src=\"seasons.jpg\">" >> $htmlout/$mediatype.html
      if [ -f "$htmlout/blue.jpg" ]; then
         rm $htmlout/blue.jpg
      fi
      if [ -f "$htmlout/orange.jpg" ]; then
         rm $htmlout/orange.jpg
      fi

   fi


   echo "</p>" >> $htmlout/$mediatype.html

   for idLoop in $idList; do

      name=`sqlite3 $dbpath/MyVideos107.db "SELECT c00 from $mediatype where $id=$idLoop"`

      if [ "$name" != "** 403: Series Not Permitted **" ]; then
         plot=`sqlite3 $dbpath/MyVideos107.db "SELECT c01 from $mediatype where $id=$idLoop"`

         if [ "$mediatype" == "tvshow" ]; then
            status=`sqlite3 $dbpath/MyVideos107.db "SELECT c02 from $mediatype where $id=$idLoop"`
            rating=`sqlite3 $dbpath/MyVideos107.db "SELECT c04 from $mediatype where $id=$idLoop"`
            firstaired=`sqlite3 $dbpath/MyVideos107.db "SELECT c05 from $mediatype where $id=$idLoop"`
            guide=`sqlite3 $dbpath/MyVideos107.db "SELECT c10 from $mediatype where $id=$idLoop"`
            contentrating=`sqlite3 $dbpath/MyVideos107.db "SELECT c13 from $mediatype where $id=$idLoop"`
            network=`sqlite3 $dbpath/MyVideos107.db "SELECT c14 from $mediatype where $id=$idLoop"`
            echo $name
         fi

         if [ "$mediatype" == "movie" ]; then
            idFile=`sqlite3 $dbpath/MyVideos107.db "SELECT idFile from $mediatype where $id=$idLoop"`
            width=`sqlite3 $dbpath/MyVideos107.db "SELECT iVideoWidth from streamdetails where idFile=\"$idFile\" and iStreamType=0"`
            height=`sqlite3 $dbpath/MyVideos107.db "SELECT iVideoHeight from streamdetails where idFile=\"$idFile\" and iStreamType=0"`
            if [ "$width" == "1920" ]; then
               width="1080p"
            elif [ "$width" == "1280" ]; then
               width="720p"
            elif [ "$width" == "640" ]; then
               width="480p"
            elif [ "$width" == "" ]; then
               width=""
            else
               width="${width}x${height}"
            fi
            filetype=`sqlite3 $dbpath/MyVideos107.db "SELECT strFilename from files where idFile=\"$idFile\""`
            filetype="${filetype: -3}"
            trailerurl=`sqlite3 $dbpath/MyVideos107.db "SELECT c19 from $mediatype where $id=$idLoop"`
            if [ "$trailerurl" != "" ]; then
               videoarg=`echo $trailerurl|awk -F"videoid=" '{print $2}'|cut -c1-11`
               trailerurl="https://www.youtube.com/watch?v=${videoarg}"
            fi
         
            studio=`sqlite3 $dbpath/MyVideos107.db "SELECT c18 from $mediatype where $id=$idLoop"`
            rating=`sqlite3 $dbpath/MyVideos107.db "SELECT c12 from $mediatype where $id=$idLoop"`
            runtime=`sqlite3 $dbpath/MyVideos107.db "SELECT c11 from $mediatype where $id=$idLoop"`
            runtime=`echo - | awk -v "S=$runtime" '{printf "%dh%dm%ds",S/(60*60),S%(60*60)/60,S%60}'`
            director=`sqlite3 $dbpath/MyVideos107.db "SELECT c15 from $mediatype where $id=$idLoop"`
            echo $name 
         fi

         out="$htmlout/$mediatype/$idLoop.html"
         if [ -f "$out" ]; then
            rm $out
         fi
         touch $out

         if [ "$mediatype" == "tvshow" ]; then
            bannerurl=`sqlite3 $dbpath/MyVideos107.db "SELECT url from art where media_id=$idLoop and type='banner' and media_type=\"$mediatype\""`
            if [ "$bannerurl" != "" ]; then
               bannerfile=$(basename $bannerurl)
               if [ ! -f "$htmlout/images/${mediatype}banners/$bannerfile" ]; then
                  wget -O $htmlout/images/${mediatype}banners/$bannerfile $bannerurl
               fi
            else
               bannerfile="unknown.jpg"
            fi
         fi

         posterfile="${idLoop}.jpg"

         #
         # if the poster art doesn't exist, do this rather complicated thing...
         #
         if [ ! -f "$htmlout/images/${mediatype}posters/${idLoop}.jpg" ]; then
            posterurl=`sqlite3 $dbpath/MyVideos107.db "SELECT url from art where media_id=$idLoop and type='poster' and media_type=\"$mediatype\""`

            if [ "$posterurl" == "" ]; then
               convert -size 150x221 xc:black $htmlout/images/${mediatype}posters/TEMP${idLoop}.jpg
               convert -background '#0008' -fill white -gravity northwest -size 150x200 caption:"${name}" $htmlout/images/${mediatype}posters/TEMP${idLoop}.jpg +swap -gravity north -composite $htmlout/images/${mediatype}posters/${idLoop}.jpg
               if [ -f "$htmlout/images/${mediatype}posters/TEMP${idLoop}.jpg" ]; then
                  rm $htmlout/images/${mediatype}posters/TEMP${idLoop}.jpg
               fi
            else
               wget -O $htmlout/images/${mediatype}posters/${idLoop}.jpg $posterurl
            fi
         
     
            convert $htmlout/images/${mediatype}posters/${posterfile} -resize 150 $htmlout/images/${mediatype}posters/TEMP0${posterfile}
            if [ -f "$htmlout/images/${mediatype}posters/${posterfile}" ]; then
               rm $htmlout/images/${mediatype}posters/${posterfile}
            fi
            mv $htmlout/images/${mediatype}posters/TEMP0${posterfile} $htmlout/images/${mediatype}posters/${posterfile}
            posterwidth=`identify -format %w $htmlout/images/${mediatype}posters/${posterfile}`

            if [ "$mediatype" == "movie" ]; then
               if [ "$width" == "" ]; then
                  imagetext="$filetype"
               else
                  imagetext="${width} | ${filetype}"
               fi
               convert -background '#0008' -fill white -gravity southeast -size ${posterwidth}x15 caption:"${imagetext}" $htmlout/images/${mediatype}posters/${posterfile} +swap -gravity south -composite $htmlout/images/${mediatype}posters/TEMP0${posterfile}

               mv $htmlout/images/${mediatype}posters/TEMP0${posterfile} $htmlout/images/${mediatype}posters/${posterfile}
               if [ -f "$htmlout/images/${mediatype}posters/TEMP0${posterfile}" ]; then
                  rm $htmlout/images/${mediatype}posters/TEMP0${posterfile}
               fi
            fi
         fi

         #
         # genres
         #
         genres=`sqlite3 $dbpath/MyVideos107.db "SELECT genre_id from genre_link where media_id=$idLoop and media_type=\"$mediatype\""`

         filegenre=""
         for genre in $genres; do
            genrename=`sqlite3 $dbpath/MyVideos107.db "SELECT name from genre where genre_id=$genre"`
            filegenre="<a href=\"../genre/$genre.html\">$genrename</a> / $filegenre"
            echo "<a href=\"../$mediatype/$idLoop.html\">" >> $htmlout/genre/$genre.$mediatype
            echo "<img width=150 src=\"../images/${mediatype}posters/$posterfile\"></a>" >> $htmlout/genre/$genre.$mediatype
         done

         if [ "$filegenre" != "" ]; then 
            filegenre=${filegenre::-3}
         fi

         echo "<a href=\"$mediatype/$idLoop.html\">" >> $htmlout/$mediatype.html
         echo "<img width=150 src=\"images/${mediatype}posters/$posterfile\"></a>" >> $htmlout/$mediatype.html

         echo "<html><head><title>$name</title>" >> $out
         echo "<link rel=\"stylesheet\" href=\"../kodisheet.css\" type=\"text/css\">" >> $out
         echo "</head>" >> $out
         echo "<body>" >> $out
         echo "<center><table width=400><tr><td>" >> $out

         if [ "$mediatype" == "tvshow" ]; then
            echo "<img src=\"../images/${mediatype}banners/$bannerfile\" width=450>" >> $out
            echo "</p>" >> $out
            echo "<p class=\"details\">" >> $out
            echo "Rating: $rating<br />" >> $out
            echo "First aired: $firstaired<br />" >> $out
            echo "Genre: $filegenre<br />" >> $out
            echo "Network: $network<br />" >> $out
            echo "Content Rating: $contentrating<br />" >> $out
            echo "</p>" >> $out
         fi
         if [ "$mediatype" == "movie" ]; then
            echo "<p class=\"showtitle\">$name</p>" >> $out
            echo "<p class=\"artwork\">" >> $out
            echo "<img src=\"../images/${mediatype}posters/$posterfile\"" >> $out
            echo "</p>" >> $out
            echo "<p class=\"details\">" >> $out
            echo "trailer: <a href=\"$trailerurl\">youtube</a><br />" >> $out
            echo "studio: $studio<br />" >> $out
            echo "rating: $rating<br />" >> $out
            echo "runtime: $runtime<br />" >> $out
            echo "genre: $filegenre<br />" >> $out
            echo "director: $director<br />" >> $out
            echo "</p>" >> $out
         fi

         echo "<p class=\"synopsis\">" >> $out
         echo "<font class=\"heading\">Plot synopsis</font><br /><br />" >> $out
         echo "$plot" >> $out
         echo "</p>" >> $out

         if [ "$mediatype" == "movie" ]; then
            echo "<p class=\"footer\">$footer<br /></p>" >> $out
            echo "</td></tr></table></center>" >> $out
            echo "</p></body></html>" >> $out
         fi

         if [ "$mediatype" == "tvshow" ]; then

            seasons=`sqlite3 $dbpath/MyVideos107.db "SELECT idSeason from seasons where idShow=$idLoop"`
            seasonsCount="0"

            episodeCount=`sqlite3 $dbpath/MyVideos107.db "SELECT count() from episode where idShow=$idLoop"`
            convert -font Arial -pointsize 18 -background 'blue' -fill white -gravity center -size 30x25 caption:"$episodeCount" $htmlout/images/${mediatype}posters/${posterfile} +swap -gravity northwest -composite $htmlout/images/${mediatype}posters/TEMP0${posterfile}

            if [ -f "$htmlout/images/${mediatype}posters/${posterfile}" ]; then
               rm $htmlout/images/${mediatype}posters/${posterfile}
            fi

            for season in $seasons; do
               count=`sqlite3 $dbpath/MyVideos107.db "SELECT count() from episode where idShow=$idLoop and idSeason=$season"`

               if [ "$count" != "0" ]; then
                  echo "<p class=\"seasonlist\">" >> $out
                  seasonNo=`sqlite3 $dbpath/MyVideos107.db "SELECT season from seasons where idShow=$idLoop and idSeason=$season"`
                  realseason=`sqlite3 $dbpath/MyVideos107.db "SELECT c12 from episode where idShow=$idLoop and idSeason=$season limit 1"`
                  file=`sqlite3 $dbpath/MyVideos107.db "SELECT c18 from episode where idShow=$idLoop and idSeason=$season"`
                  echo "<Font class=\"heading\">Season $realseason</font>" >> $out
                  echo "<br /><br />" >> $out

                  episodes=`sqlite3 $dbpath/MyVideos107.db "select idEpisode from episode where idShow=$idLoop and idSeason=$season"`
                  seasonsCount=$((seasonsCount+1))

                  for episode in $episodes; do
                     episodeNo=`sqlite3 $dbpath/MyVideos107.db "SELECT c13 from episode where idShow=$idLoop and idSeason=$season and idEpisode=$episode"`
                     episodeTitle=`sqlite3 $dbpath/MyVideos107.db "SELECT c00 from episode where idShow=$idLoop and idSeason=$season and idEpisode=$episode"`
                     echo "$episodeNo. $episodeTitle<br />" >> $out
                  done
                  echo "</p>" >> $out
               fi
            done
            convert -font Arial -pointsize 18 -background 'orange' -fill white -gravity center -size 30x25 caption:"$seasonsCount"  $htmlout/images/${mediatype}posters/TEMP0${posterfile} +swap -gravity northeast -composite $htmlout/images/${mediatype}posters/${posterfile}
            if [ -f "$htmlout/images/${mediatype}posters/TEMP0${posterfile}" ]; then
               rm $htmlout/images/${mediatype}posters/TEMP0${posterfile}
            fi

      echo "<p class=\"footer\">$footer<br /></p>" >> $out
            echo "</td></tr></table></center>" >> $out
      echo "</p></body></html>" >> $out
         fi
      fi
   done
      echo "</p><p class=\"footer\">$footer" >> $htmlout/$mediatype.html
      echo "</p><br /></body></html>" >> $htmlout/$mediatype.html

   #
   # 
   #
   genres=`sqlite3 $dbpath/MyVideos107.db "SELECT genre_id from genre"`
   for genre in $genres; do
      if [ -f "$htmlout/genre/$genre.html" ]; then
         genrename=`sqlite3 $dbpath/MyVideos107.db "SELECT name from genre where genre_id=$genre"`
         if [ -f "$htmlout/genre/$genre.$mediatype" ]; then
            echo "<p class="artwork"><font class=\"giantheading\">$indextitle</font><br /><br />" >> $htmlout/genre/$genre.html
            cat $htmlout/genre/$genre.$mediatype >> $htmlout/genre/$genre.html
            echo "<br /><br /></p>" >> $htmlout/genre/$genre.html
            rm $htmlout/genre/$genre.$mediatype
         fi
      fi
   done


done

#
# complete the HTML footers for all the genre files
#
genres=`sqlite3 $dbpath/MyVideos107.db "SELECT genre_id from genre"`
for genre in $genres; do
   if [ -f "$htmlout/genre/$genre.html" ]; then
      echo "</body></html>" >> $htmlout/genre/$genre.html
   fi
done


#
# index page
#

if [ -f "$htmlout/index.html" ]; then
   rm $htmlout/index.html
fi
touch $htmlout/index.html

if [ -f "$htmlout/recent.html" ]; then
   rm $htmlout/recent.html
fi
touch $htmlout/recent.html

datestamps=""

#for ((day=0;day<$lastDays;day++)); do
#   ago=`date +%Y-%m-%d --date "$day day ago"`
#   datestamps="$ago $datestamps"
#done

echo "<html><head><title>Kodisheet $VERSION</title>" >> $htmlout/index.html
echo "<link rel=\"stylesheet\" href=\"kodisheet.css\" type=\"text/css\">" >> $htmlout/index.html
echo "</head><body>" >> $htmlout/index.html
echo "<p class=\"navigaton\"><br />" >> $htmlout/index.html
echo "<font class=\"giantheading\">Home " >> $htmlout/index.html
echo " | " >> $htmlout/index.html

echo "<a href=\"tvshow.html\">TV Shows</a> [$tvCount]" >> $htmlout/index.html
echo " | " >> $htmlout/index.html
echo "<a href=\"movie.html\">Movies</a> [$movieCount]" >> $htmlout/index.html
echo " | " >> $htmlout/index.html
echo "<a href=\"genre/index.html\">All Genres</a>" >> $htmlout/index.html
echo " | " >> $htmlout/index.html
echo "<a href=\"recent.html\">Last $lastDays days</a>" >> $htmlout/index.html
echo "<br /><br /></font>" >> $htmlout/index.html

echo "<font class=\"heading\">Recently added movies</font>" >> $htmlout/index.html
echo "</font><br /><br />" >> $htmlout/index.html

echo "<html><head><title>Recently Added</title>" >> $htmlout/recent.html
echo "<link rel=\"stylesheet\" href=\"kodisheet.css\" type=\"text/css\">" >> $htmlout/recent.html
echo "</head>" >> $htmlout/recent.html
echo "<body><center><table width=500>" >> $htmlout/recent.html
echo "<tr><td colspan=2><br /><font class=\"giantheading\">Recently added movies</font><br /><br /></td></tr>" >> $htmlout/recent.html

datestamps=`sqlite3 $dbpath/MyVideos107.db "select DISTINCT(substr(dateAdded,1,10)) from files ORDER BY dateAdded DESC LIMIT $lastDays"`
for datestamp in $datestamps; do
   files=`sqlite3 $dbpath/MyVideos107.db "select idFile from files where dateAdded LIKE \"$datestamp %%:%%:%%\""`
   for file in $files; do
      findMovie=`sqlite3 $dbpath/MyVideos107.db "select count() from movie where idFile=$file"`
      if [ "$findMovie" != "0" ]; then
         idMovie=`sqlite3 $dbpath/MyVideos107.db "select idMovie from movie where idFile=$file"`
         c00=`sqlite3 $dbpath/MyVideos107.db "select c00 from movie where idFile=$file"`
         echo $c00
         plot=`sqlite3 $dbpath/MyVideos107.db "SELECT c01 from movie where idMovie=$idMovie"`
         trailerurl=`sqlite3 $dbpath/MyVideos107.db "SELECT c19 from movie where idMovie=$idMovie"`
         if [ "$trailerurl" != "" ]; then
            videoarg=`echo $trailerurl|awk -F"videoid=" '{print $2}'|cut -c1-11`
            trailerurl="https://www.youtube.com/watch?v=${videoarg}"
         fi

         studio=`sqlite3 $dbpath/MyVideos107.db "SELECT c18 from movie where idMovie=$idMovie"`
         rating=`sqlite3 $dbpath/MyVideos107.db "SELECT c12 from movie where idMovie=$idMovie"`
         runtime=`sqlite3 $dbpath/MyVideos107.db "SELECT c11 from movie where idMovie=$idMovie"`
         runtime=`echo - | awk -v "S=$runtime" '{printf "%dh%dm%ds",S/(60*60),S%(60*60)/60,S%60}'`
         director=`sqlite3 $dbpath/MyVideos107.db "SELECT c15 from movie where idMovie=$idMovie"`

         echo "<a href=\"movie/$idMovie.html\">" >> $htmlout/index.html
         echo "<img src=\"images/movieposters/$idMovie.jpg\">" >> $htmlout/index.html
         echo "</a>" >> $htmlout/index.html

         echo "<tr><td valign=top><a href=\"movie/$idMovie.html\">" >> $htmlout/recent.html
         echo "<img src=\"images/movieposters/$idMovie.jpg\">" >> $htmlout/recent.html
         echo "</a></td>" >> $htmlout/recent.html
         echo "<td><p class=\"showtitle\">$c00</p>" >> $htmlout/recent.html
         echo "<p class=\"details\">" >> $htmlout/recent.html
         echo "trailer: <a href=\"$trailerurl\">youtube</a><br />" >> $htmlout/recent.html
         echo "studio: $studio<br />" >> $htmlout/recent.html
         echo "rating: $rating<br />" >> $htmlout/recent.html
         echo "runtime: $runtime<br />" >> $htmlout/recent.html
         echo "genre: $filegenre<br />" >> $htmlout/recent.html
         echo "director: $director<br />" >> $htmlout/recent.html
         echo "<br /><br />" >> $htmlout/recent.html
         echo "$plot" >> $htmlout/recent.html
         echo "<br /><br /></td></tr>" >> $htmlout/recent.html

      fi
   done
done

echo "<br /><br />" >> $htmlout/index.html
echo "<font class=\"heading\">Recently added TV</font>" >> $htmlout/index.html
echo "</font><br /><br />" >> $htmlout/index.html

reqstr=""

for datestamp in $datestamps; do
   files=`sqlite3 $dbpath/MyVideos107.db "select idFile from files where dateAdded LIKE \"$datestamp %%:%%:%%\""`
   prevShow=""
   prevseason=""
   for file in $files; do
      findShow=`sqlite3 $dbpath/MyVideos107.db "select count() from episode where idFile=$file"`
      if [ "$findShow" != "0" ]; then
         idShow=`sqlite3 $dbpath/MyVideos107.db "select idShow from episode where idFile=$file"`
         reqstr="$reqstr $idShow:$file"
      fi
   done
done

showlist=`for i in $reqstr; do echo $i; done | sort`

prevShow=""
prevseason=""

for show in $showlist; do
   file=`echo $show|awk -F":" '{print $2}'`
   idShow=`echo $show|awk -F":" '{print $1}'`

   idShow=`sqlite3 $dbpath/MyVideos107.db "select idShow from episode where idFile=$file"`
   c00=`sqlite3 $dbpath/MyVideos107.db "select c00 from tvshow where idShow=$idShow"`
   c01=`sqlite3 $dbpath/MyVideos107.db "select c01 from episode where idFile=$file"`
   showc00=`sqlite3 $dbpath/MyVideos107.db "select c00 from episode where idFile=$file"`
   c18=`sqlite3 $dbpath/MyVideos107.db "select c18 from episode where idFile=$file"`

   if [ "$idShow" != "$prevShow" ]; then
      if [ "$prevshow" != "" ]; then
         echo "</td></tr>" >> $htmlout/recent.html
      fi
      echo $c00
      prevShow="$idShow"

      echo "<a href=\"tvshow/$idShow.html\">" >> $htmlout/index.html
      echo "<img src=\"images/tvshowposters/$idShow.jpg\">" >> $htmlout/index.html
      echo "</a>" >> $htmlout/index.html

      bannerurl=`sqlite3 $dbpath/MyVideos107.db "SELECT url from art where media_id=$idShow and type='banner' and media_type=\"tvshow\""`
      bannerfile=$(basename $bannerurl)
      echo "<tr><td colspan=2><br /><a href=\"tvshow/$idShow.html\">" >> $htmlout/recent.html
      echo "<img width=450 src=\"images/tvshowbanners/$bannerfile\">" >> $htmlout/recent.html
      echo "</a><br /></td></tr><tr><td colspan=2>" >> $htmlout/recent.html
      prevseason=""
   fi

   epno=$(basename "$c18")
   epno=${epno:4:2}
   season=$(basename "$c18")
   season=${season:1:2}

   if [ "$prevseason" != "$season" ]; then
      if [ "${season:0:1}" == "0" ]; then
         displayseason=${season:1:1}
      else
         displayseason=$season
      fi
      echo "<font class=\"heading\">Season $displayseason</font><br /><br />" >> $htmlout/recent.html
      prevseason=$season
   fi
   echo "<font class=\"bodytext\">$epno $showc00</font><br />" >> $htmlout/recent.html
done

echo "</p><p class=\"footer\">$footer" >> $htmlout/index.html
echo "</p><br /></body></html>" >> $htmlout/index.html

echo "<tr><td colspan=2><br /><p class=\"footer\">$footer</font></br ></td></tr>" >> $htmlout/recent.html
echo "</center></body></html>" >> $htmlout/recent.html

